defaults: &defaults
  :log_level: warn
  :cassandra:
    :host: localhost
    :port: 9160
    :keyspace: Twitter

:development:
  <<: *defaults
  :log_level: debug

:test:
  <<: *defaults

:production:
  <<: *defaults
